include("extreme_structures/AbstractFittedExtremeValueModel.jl")
include("extreme_structures/BayesianAbstractExtremeValueModel.jl")
include("extreme_structures/MaximumLikelihoodAbstractExtremeValueModel.jl")
include("extreme_structures/pwmAbstractExtremeValueModel.jl")