name: Documentation

on:
  push:
    branches:
      - main     # Pushes to main
      - dev      # Pushes to dev
    tags: '*'     # Any tag

  pull_request:
    branches:
      - main     # PRs targeting main
      - dev      # PRs targeting dev

jobs:
  build:
    permissions:
      actions: write
      contents: write
      pull-requests: read
      statuses: write
      
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Julia
        uses: julia-actions/setup-julia@latest
        with:
          version: '1'

      - name: Install dependencies
        run: julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'

      - name: Build and deploy documentation
        env:
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: julia --project=docs/ docs/make.jl
